[package]
name = "crussh-cli"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crussh = {path = "../crussh"}
rustyline = "9.0.0"
home = "0.5.3"
whoami = "0.1.0"
colored = "2.0.0"